### ISSUE TITLE
Add sqlite db w/ slick for saving report info

### ISSUE THREAD

**Issue by inakianduaga** [inakianduaga/scala-image-processor#7]
Heroku has a 30 sec maximum execution time, so we need to make the processing async and keep state in a db

https://gist.github.com/larste/6683694

**Comment by inakianduaga** [comment]
# Update: Better use websockets

Actually if we use websockets we can push the report results over the websocket, and we wouldn't need the database. This should be quite simple and with almost no changes to the frontend

https://www.playframework.com/documentation/2.4.x/ScalaWebSockets

### Bacon.js for reactive websockets

http://blog.scottlogic.com/2014/07/23/frp-with-bacon-and-d3.html

**Comment by inakianduaga** [comment]
# TODO:
- [x] Modify actor creation to use the random websocket id available in the session.

Deprecated below
- [x] After connection, send from the server a websocket ID to the client that needs to be included in each request to get updates pushed back to the client (otherwise we need to do this using [Session Ids](https://www.playframework.com/documentation/2.4.x/ScalaSessionFlash))
- [x] Find a way to assign names to the actors we create, and to fetch actors by name as well (where name would be the unique id we want)

Scala examples

http://alvinalexander.com/scala/simple-scala-akka-actor-examples-hello-world-actors

### Looking up actors

Since each actor has a path (unique), we can search for it by doing

``` scaka
import play.api.libs.concurrent.Akka 
import play.api.Play.current

// some code
val what = Akka.system.actorSelection("some path")
```

and presumably we can use that to tell the actor to do something

We should also be able to retrieve the name of a given actor

**Comment by inakianduaga** [comment]
# Update:

Check typesafe's activator `ReactiveMaps` project that explains the actor & websocket
